version: '3.8'
services:
  db:
    image: postgres:15
    container_name: lab3-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/02-data.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab3-app
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab3
      DB_HOST: db
    command: ["sh", "-c", "./scripts/wait-for-db.sh db python3 models.py"]

volumes:
  postgres_data:
